### ISSUE TITLE
Exception in IDEA Ultimate 2019.1.1

### ISSUE THREAD

**Issue by cwilso03** [hsz/idea-nodesecurity#14]
### Prerequisites

* [x ] Plugin is in the latest version
* [x ] Issue was not reported yet
* [x ] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

IDEA is catching an error several times a day with the same stack trace (below).

```
java.lang.RuntimeException: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 0, column 53: Expected data for a mobi.hsz.idea.nodesecurity.models.YarnLock field but found: scalar
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:101)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitRestElementsAndCleanup(LocalInspectionsPass.java:331)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:201)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:117)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 0, column 53: Expected data for a mobi.hsz.idea.nodesecurity.models.YarnLock field but found: scalar
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:437)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:138)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:105)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:92)
	at mobi.hsz.idea.nodesecurity.scanner.YarnLockProvider.<init>(YarnLockProvider.kt:23)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.createProvider(LockProvider.kt:31)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.access$createProvider(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$getProvider$$inlined$map$lambda$1.invoke(LockProvider.kt:19)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$getProvider$$inlined$map$lambda$1.invoke(LockProvider.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.getProvider(LockProvider.kt:20)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.access$getProvider(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$get$1.invoke(LockProvider.kt:16)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$get$1.invoke(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.utils.UtilsKt$memoize$1.invoke(Utils.kt:42)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1$2.invoke(VulnerabilitiesScanner.kt:30)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1$2.invoke(VulnerabilitiesScanner.kt:13)
	at mobi.hsz.idea.nodesecurity.scanner.AdvisoryReference.or(AdvisoryReference.kt:11)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1.invoke(VulnerabilitiesScanner.kt:30)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1.invoke(VulnerabilitiesScanner.kt:13)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$mapDependencies$1.doResume(VulnerabilitiesScanner.kt:57)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at mobi.hsz.idea.nodesecurity.codeInspection.VulnerabilityInspection.doCheckFile(VulnerabilityInspection.kt:44)
	at mobi.hsz.idea.nodesecurity.codeInspection.VulnerabilityInspection.checkFile(VulnerabilityInspection.kt:17)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$8(LocalInspectionsPass.java:319)
	at com.intellij.util.AstLoadingFilter.lambda$toComputable$2(AstLoadingFilter.java:169)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:111)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitRestElementsAndCleanup$9(LocalInspectionsPass.java:318)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	... 4 more
```

### Steps to Reproduce

I'm not sure what triggers the error.  It happens somewhat randomly, presumably as a background process kicks off.

**Expected behavior:** Error not to be thrown/caught.

**Actual behavior:** IDEA reports the above error.

**Reproduces how often:** Several times a day.

### Versions

**Plugin:** 

```
0.4.0
```

**IDE:** 

```
IntelliJ IDEA 2019.1.1 (Ultimate Edition)
Build #IU-191.6707.61, built on April 16, 2019
JRE: 1.8.0_202-release-1483-b44 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**OS:** 

```
Windows 10 Enterprise
```

### Additional Information

n/a

**Comment by cwilso03** [comment]
This exception is still present in IDEA Ultimate 2019.3.2.
