### ISSUE TITLE
Error installing it on PHPStorm 2019.1.2

### ISSUE THREAD

**Issue by icarrasco** [hsz/idea-nodesecurity#15]
### Prerequisites

* [X ] Plugin is in the latest version: 0.4.0
* [X ] Issue was not reported yet
* [ X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

Just after installing the plugin via marketplace and restart the IDE, the error is thrown

```
java.lang.RuntimeException: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 0, column 24: Unable to find property '@types/node@^10.12.18' on class: mobi.hsz.idea.nodesecurity.models.YarnLock
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:101)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:56)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:266)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:198)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:117)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:430)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:422)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:398)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:396)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:174)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 0, column 24: Unable to find property '@types/node@^10.12.18' on class: mobi.hsz.idea.nodesecurity.models.YarnLock
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:374)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:138)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:105)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:92)
	at mobi.hsz.idea.nodesecurity.scanner.YarnLockProvider.<init>(YarnLockProvider.kt:23)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.createProvider(LockProvider.kt:31)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.access$createProvider(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$getProvider$$inlined$map$lambda$1.invoke(LockProvider.kt:19)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$getProvider$$inlined$map$lambda$1.invoke(LockProvider.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.getProvider(LockProvider.kt:20)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.access$getProvider(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$get$1.invoke(LockProvider.kt:16)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$get$1.invoke(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.utils.UtilsKt$memoize$1.invoke(Utils.kt:42)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1$2.invoke(VulnerabilitiesScanner.kt:30)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1$2.invoke(VulnerabilitiesScanner.kt:13)
	at mobi.hsz.idea.nodesecurity.scanner.AdvisoryReference.or(AdvisoryReference.kt:11)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1.invoke(VulnerabilitiesScanner.kt:30)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1.invoke(VulnerabilitiesScanner.kt:13)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$mapDependencies$1.doResume(VulnerabilitiesScanner.kt:57)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at mobi.hsz.idea.nodesecurity.codeInspection.VulnerabilityInspection.doCheckFile(VulnerabilityInspection.kt:44)
	at mobi.hsz.idea.nodesecurity.codeInspection.VulnerabilityInspection.checkFile(VulnerabilityInspection.kt:17)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:142)
	at com.intellij.extapi.psi.PsiFileBase.accept(PsiFileBase.java:70)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:295)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:263)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:260)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:260)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:586)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:86)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	... 4 more
```

### Steps to Reproduce

1. Find the plugin and install on Marketplace
2. Restart the IDE
3. Open a project

### Versions

**Plugin:** 

```
0.4.0
```

**IDE:** 

```
PHP Storm  2019.1.2
```

**OS:** 

```
OSX 10.14.4
```

### Additional Information

Just using it in a simple project boilerplate using yarn

**Comment by manishmaharjan** [comment]
Similar issue also happening with PHP Storm 2019.1.3
