### ISSUE TITLE
Error executing task com.intellij.openapi.project.DumbServiceImpl$$Lambda$

### ISSUE THREAD

**Issue by kryton** [hsz/idea-nodesecurity#19]
### Prerequisites

* [x] Plugin is in the latest version
* [X] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

I created a boilerplate app

$ yarn create apollo-app my-app

selected @server 
then opened up a terminal and did a 'yarn start'

```
Stack trace if available.
```
Error executing task com.intellij.openapi.project.DumbServiceImpl$$Lambda$1508/0x00000008013d4440@4734f8ab

com.esotericsoftware.yamlbeans.YamlReader$YamlReaderException: Line 0, column 37: Unable to find property '@apollographql/apollo-tools@^0.3.3' on class: mobi.hsz.idea.nodesecurity.models.YarnLock
	at com.esotericsoftware.yamlbeans.YamlReader.readValueInternal(YamlReader.java:374)
	at com.esotericsoftware.yamlbeans.YamlReader.readValue(YamlReader.java:138)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:105)
	at com.esotericsoftware.yamlbeans.YamlReader.read(YamlReader.java:92)
	at mobi.hsz.idea.nodesecurity.scanner.YarnLockProvider.<init>(YarnLockProvider.kt:23)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.createProvider(LockProvider.kt:31)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.access$createProvider(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$getProvider$$inlined$map$lambda$1.invoke(LockProvider.kt:19)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$getProvider$$inlined$map$lambda$1.invoke(LockProvider.kt:15)
	at kotlin.SynchronizedLazyImpl.getValue(Lazy.kt:131)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.getProvider(LockProvider.kt:20)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion.access$getProvider(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$get$1.invoke(LockProvider.kt:16)
	at mobi.hsz.idea.nodesecurity.scanner.LockProvider$Companion$get$1.invoke(LockProvider.kt:15)
	at mobi.hsz.idea.nodesecurity.utils.UtilsKt$memoize$1.invoke(Utils.kt:42)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1$2.invoke(VulnerabilitiesScanner.kt:30)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1$2.invoke(VulnerabilitiesScanner.kt:13)
	at mobi.hsz.idea.nodesecurity.scanner.AdvisoryReference.or(AdvisoryReference.kt:11)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1.invoke(VulnerabilitiesScanner.kt:30)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$scanFile$$inlined$let$lambda$1.invoke(VulnerabilitiesScanner.kt:13)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion$mapDependencies$1.doResume(VulnerabilitiesScanner.kt:57)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at mobi.hsz.idea.nodesecurity.scanner.VulnerabilitiesScanner$Companion.isFileVulnerable(VulnerabilitiesScanner.kt:20)
	at mobi.hsz.idea.nodesecurity.components.NodeSecurityProjectComponent$verifyFile$1.run(NodeSecurityProjectComponent.kt:55)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:835)
	at mobi.hsz.idea.nodesecurity.components.NodeSecurityProjectComponent.verifyFile(NodeSecurityProjectComponent.kt:54)
	at mobi.hsz.idea.nodesecurity.components.NodeSecurityProjectComponent.access$verifyFile(NodeSecurityProjectComponent.kt:21)
	at mobi.hsz.idea.nodesecurity.components.NodeSecurityProjectComponent$projectOpened$1.run(NodeSecurityProjectComponent.kt:42)
	at com.intellij.openapi.project.DumbServiceImpl.unsafeRunWhenSmart(DumbServiceImpl.java:221)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:207)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:348)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:340)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:100)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

### Steps to Reproduce

1. _First Step_
2. _Second Step_
3. _and so on..._

**Expected behavior:** _What you expect to happen_

**Actual behavior:** _What actually happens_

**Reproduces how often:** _What percentage of the time does it reproduce?_

### Versions

**Plugin:** 

```
Can be found in Settings > Plugins > .ignore
```

**IDE:** 

```
Can be found in Help > About. Click on the copy icon on the left.
```

**OS:** 

```
Information about operation system - type, version.
```

### Additional Information

_Any additional information, configuration or data that might be necessary to reproduce the issue._

**Comment by kryton** [comment]
Version: 0.4.0
IDE: IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 24, 2020
Licensed to Ian Holsman
Subscription is active until April 1, 2021
Runtime version: 11.0.8+10-b944.31 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 10.15.6
GC: ParNew, ConcurrentMarkSweep
Memory: 1979M
Cores: 12
Non-Bundled Plugins: io.rangaofei, com.jinsihou.react.snippets, mobi.hsz.idea.nodesecurity, org.zalando.intellij.swagger, org.toml.lang, org.jetbrains.kotlin, org.intellij.scala, com.intellij.lang.jsgraphql, Pythonid, org.jetbrains.plugins.go, org.rust.lang

OS: OS/X - 10.15.6
