### ISSUE TITLE
Unexpected token 'OR(|) at position 7', expecting '[NUMERIC(^(0|[1-9][0-9]*))]'

### ISSUE THREAD

**Issue by pkuczynski** [hsz/idea-nodesecurity#5]
I am getting this error for all my projects:

```
null
Unexpected token 'OR(|) at position 7', expecting '[NUMERIC(^(0|[1-9][0-9]*))]'
	at com.github.zafarkhaja.semver.expr.ExpressionParser.consumeNextToken(ExpressionParser.java:507)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parseVersion(ExpressionParser.java:413)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parseComparisonRange(ExpressionParser.java:217)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parseRange(ExpressionParser.java:174)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parseSemVerExpression(ExpressionParser.java:118)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parseMoreExpressions(ExpressionParser.java:141)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parseSemVerExpression(ExpressionParser.java:120)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parse(ExpressionParser.java:87)
	at com.github.zafarkhaja.semver.expr.ExpressionParser.parse(ExpressionParser.java:43)
	at com.github.zafarkhaja.semver.Version.satisfies(Version.java:325)
	at mobi.hsz.idea.nodesecurity.models.Advisory.isVulnerable(Advisory.kt:38)
	at mobi.hsz.idea.nodesecurity.utils.VulnerabilitiesScanner$Companion$scan$1.doResume(VulnerabilitiesScanner.kt:29)
	at kotlin.coroutines.experimental.jvm.internal.CoroutineImpl.resume(CoroutineImpl.kt:54)
	at kotlin.coroutines.experimental.SequenceBuilderIterator.hasNext(SequenceBuilder.kt:129)
	at mobi.hsz.idea.nodesecurity.components.NodeSecurityProjectComponent$projectOpened$1.run(NodeSecurityProjectComponent.kt:25)
```

Here come full error log and example `package.json`: https://gist.github.com/pkuczynski/4f706d9fbc20b346734ff945b3e96ce5

**Comment by hsz** [comment]
@pkuczynski   Thank you for the report (and sorry for delay!). Issue is fixed and will be released with v0.3.

**Comment by pkuczynski** [comment]
@InkedCurtis? :)

**Comment by hsz** [comment]
@pkuczynski Sorry, it's late ;-) I made the similar comment to the duplicated issue.

**Comment by pkuczynski** [comment]
I guessed :) Good work so far! Thanks!

**Comment by hsz** [comment]
Released with v0.3.0

**Comment by pkuczynski** [comment]
Do you maybe know when this version will become available in JetBrains repo? My WebStorm still does not find it...

**Comment by hsz** [comment]
@pkuczynski 

3 minutes ago I got an e-mail

> Version 0.3.0 of the Node Security plugin has been approved by JetBrains and is now publicly available by the following link: https://plugins.jetbrains.com/plugin/10386-node-security/update/43003.
